### PR TITLE
Correctly handle transport-padding after boundaries.

### LINKED ISSUE #25: Consider allowing whitespaces after the boundary and before the CRLF
(This is a continuation of #24 )

Hello. I open this issue to ask if the following kind of boundary may be supported:

imagen
_(where the boundary is `simple_boundary`)_

This boundary ends with SPACE+CRLF.

Currently I get the following error when trying to parse a payload with that boundary:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: multer: Multipart stream is incomplete'
```

Is that kind of boundary standard compliant?

My current workaround is to make multer to process an arbitrary boundary, not ideal but will work meanwhile.

As a reference, I have tried [multipart crate](https://github.com/abonander/multipart) with a similar result, but Python [request-toolbet](https://github.com/requests/toolbelt) processes that boundary without issues.

Thanks :)

### PR DESCRIPTION
**Pull request by jebrosen**
Fixes #25.

I'm also installing `cargo-fuzz` so that I can try it out with these changes and (if wanted) add some transport-padding to the seeds.

### CODE REVIEW

File: tests/integration.rs [hunk 1]
```diff
@@ -63,6 +63,22 @@ async fn test_multipart_clean_field() {
     assert!(m.next_field().await.unwrap().is_none());
 }
 
+#[tokio::test]
+async fn test_multipart_transport_padding() {
+    let data = "--X-BOUNDARY \t \r\nContent-Disposition: form-data; name=\"my_text_field\"\r\n\r\nabcd\r\n--X-BOUNDARY     \r\nContent-Disposition: form-data; name=\"my_file_field\"; filename=\"a-text-file.txt\"\r\nContent-Type: text/plain\r\n\r\nHello world\nHello\r\nWorld\rAgain\r\n--X-BOUNDARY\t\t\t\t\t--\r\n";
```
Comment (jebrosen) [inline tests/integration.rs:68]: TODO: `--` should be *before* the transport padding, not after it. I got this switched around in both the test and the parser changes.

**Comment by rousan** [comment]
@jebrosen , @SergioBenitez , any plan for new release?

**Comment by SergioBenitez** [comment]
@rousan Yes, very soon. I also have a few updates to multer itself that break compatibility that I'd like to get in before the release. I'll update you within a week's time.

**Comment by SergioBenitez** [comment]
@jebrosen Could you rebase on `master`? Then this should be ready for a release.

File: src/multipart.rs [hunk 2]
```diff
@@ -314,10 +314,38 @@ impl Stream for Multipart {
                 return Poll::Ready(None);
             }
 
-            if &boundary_bytes[..] != format!("{}{}{}", constants::BOUNDARY_EXT, boundary, constants::CRLF).as_bytes() {
-                return Poll::Ready(Some(Err(crate::Error::IncompleteStream)));
+            if &boundary_bytes[..] == format!("{}{}{}", constants::BOUNDARY_EXT, boundary, constants::CRLF).as_bytes() {
+                state.stage = StreamingStage::ReadingFieldHeaders;
             } else {
+                state.stage = StreamingStage::ReadingTransportPadding;
```
Comment (jebrosen) [inline src/multipart.rs:320]: This... doesn't seem quite right. I believe this will accept up to two additional arbitrary bytes:

```
--boundaryzz   \t\r\n
<data>
```

However, RFC 2046 does also say:

```
NOTE TO IMPLEMENTORS:  Boundary string comparisons must compare the
   boundary value with the beginning of each candidate line.  An exact
   match of the entire candidate line is not required; it is sufficient
   that the boundary appear in its entirety following the CRLF.
```

This "NOTE" has confused me more than if it had been left out. The boundary must take the form `--boundary[optional LWSP]CRLF`, but it is also sufficient to check only for `--boundary[...]`?

Comment (jebrosen) [reply src/multipart.rs:320]: The reason this is tricky for parsing is because we need to grab the two bytes following the boundary in case they are `--` (ending the stream). However if they are anything other than `--` those two bytes need to be "un-consumed" before transitioning to `ReadingTransportPadding` or handled directly here.

File: src/multipart.rs [hunk 3]
```diff
@@ -307,17 +307,59 @@ impl Stream for Multipart {
...
+            if &boundary_bytes[..] == format!("{}{}", constants::BOUNDARY_EXT, boundary).as_bytes() {
+                state.stage = StreamingStage::DeterminingBoundaryType;
+            } else {
+                return Poll::Ready(Some(Err(crate::Error::IncompleteStream)));
+            }
+        }
+
+        if state.stage == StreamingStage::DeterminingBoundaryType {
+            let ext_len = constants::BOUNDARY_EXT.len();
+            let next_bytes = match stream_buffer.peek_exact(ext_len) {
```
Comment (jebrosen) [inline src/multipart.rs:319]: I *think* this check is necessary (including the new `peek_exact` function) to verify that it is `--boundary--` or `--boundary[whitespace]CRLF` and not `--boundaryZZ...`, but I would love to be proven wrong.

File: src/buffer.rs [hunk 4]
```diff
@@ -63,6 +63,14 @@ impl StreamBuffer {
         }
     }
 
+    pub fn peek_exact(&mut self, size: usize) -> Option<&[u8]> {
+        if size <= self.buf.len() {
+            Some(&self.buf[..size])
+        } else {
+            None
+        }
+    }
```
Comment (SergioBenitez) [inline src/buffer.rs:72]:
```suggestion
        self.buf.get(..size)
```

File: src/buffer.rs [hunk 5]
```diff
@@ -71,6 +79,19 @@ impl StreamBuffer {
         twoway::find_bytes(&self.buf, pattern).map(|idx| self.buf.split_to(idx).freeze())
     }
 
+    pub fn read_transport_padding(&mut self) -> bool {
+        match self.buf.iter().enumerate().find(|(_, b)| **b != b' ' && **b != b'\t') {
```
Comment (SergioBenitez) [inline src/buffer.rs:83]: Use `self.buf.iter().position()` instead, which does this without the tuple.

I'm always surprised there's no `.find()` on `&[u8]`.

File: src/multipart.rs [hunk 6]
```diff
@@ -307,17 +307,59 @@ impl Stream for Multipart {
...
+            } else {
+                state.stage = StreamingStage::ReadingTransportPadding;
             }
+        }
 
-            if &boundary_bytes[..] != format!("{}{}{}", constants::BOUNDARY_EXT, boundary, constants::CRLF).as_bytes() {
-                return Poll::Ready(Some(Err(crate::Error::IncompleteStream)));
-            } else {
+        if state.stage == StreamingStage::ReadingTransportPadding {
+            if !stream_buffer.read_transport_padding() {
```
Comment (SergioBenitez) [inline src/multipart.rs:339]: The naming of `read_transport_padding` confused me. This block seems to say: if you don't read transport padding and we're not at EOF, go into pending. That is, require transport padding.

But really, we just want to keep skipping padding until there's something that's not LWSP. So really, `!read_transport_padding` is saying "until there's non-LWSP". Can we name it something like that?

**Review by SergioBenitez — CHANGES_REQUESTED** [review]
Some minor changes, but otherwise looks really good to me!

File: src/multipart.rs (hunk 6 above)
Comment (jebrosen) [reply src/multipart.rs:339]: Naming this function was tough. Would something like `eat_transport_padding` or `advance_past_transport_padding` be better?
